// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv0eOLm9ju0x5OnDkMfg5aP2PlpQfMMtc',
    appId: '1:788543987645:web:db4d6f073e5f89f363bcd4',
    messagingSenderId: '788543987645',
    projectId: 'app-gotuk',
    authDomain: 'app-gotuk.firebaseapp.com',
    storageBucket: 'app-gotuk.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATWP2zO78tPToWZZq-GjZo1OKwf2r9cTk',
    appId: '1:788543987645:android:be8063654c13912163bcd4',
    messagingSenderId: '788543987645',
    projectId: 'app-gotuk',
    storageBucket: 'app-gotuk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0Dq8K07jGMpGPnBgLxorNrdq82klfL4A',
    appId: '1:788543987645:ios:241b04e5dc80a3b563bcd4',
    messagingSenderId: '788543987645',
    projectId: 'app-gotuk',
    storageBucket: 'app-gotuk.appspot.com',
    iosBundleId: 'com.gotuk.gotuk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0Dq8K07jGMpGPnBgLxorNrdq82klfL4A',
    appId: '1:788543987645:ios:c218a8a1c53529be63bcd4',
    messagingSenderId: '788543987645',
    projectId: 'app-gotuk',
    storageBucket: 'app-gotuk.appspot.com',
    iosBundleId: 'com.example.gotuk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv0eOLm9ju0x5OnDkMfg5aP2PlpQfMMtc',
    appId: '1:788543987645:web:ce1fbee567acd6da63bcd4',
    messagingSenderId: '788543987645',
    projectId: 'app-gotuk',
    authDomain: 'app-gotuk.firebaseapp.com',
    storageBucket: 'app-gotuk.appspot.com',
  );
}
