default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "Runner.xcodeproj")
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_app_store
    update_project_team(path: "Runner.xcodeproj", teamid: "57X9MD32BX")
        increment_build_number(xcodeproj: "Runner.xcodeproj")
        build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
        build_app
        api_key = app_store_connect_api_key
        upload_to_testflight(api_key: api_key)
  end
end

platform :ios do
  ENV['ITMSTRANSPORTER_FORCE_ITMS_PACKAGE_UPLOAD'] = 'false'

  desc "Push a new beta build to TestFlight"
  lane :matchlane do
    setup_ci if ENV['CI']
    match(type: 'appstore')
    update_code_signing_settings(
      code_sign_identity: "iPhone Distribution",
      profile_name: "match AppStore com.gotuk.gotuk"
    )
  end
end


