# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "Runner.xcodeproj")
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_app_store
  end
end



platform :ios do
  ENV['ITMSTRANSPORTER_FORCE_ITMS_PACKAGE_UPLOAD'] = 'false'

  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci if ENV['CI']
    match(type: 'appstore')
    update_code_signing_settings(
      code_sign_identity: "iPhone Distribution",
      profile_name: "match AppStore com.gotuk.gotuk"
    )
    update_project_team(path: "App.xcodeproj", teamid: "57X9MD32BX")
    increment_version_number_in_plist(version_number: ENV["PACKAGE_VERSION"])
    build_app
    api_key = app_store_connect_api_key
    upload_to_testflight(api_key: api_key)
  end
end


