name: android starter workflow

on:
  push:
    branches: [ "android" ]
  pull_request:
    branches: [ "android" ]

env:
  AAAA: "${{vars.AAA}}"

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          ref: 'bdd08b7337db45aa04f93e612c77e0f680c95231'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml # path to pubspec.yaml
      - run: flutter gen-l10n
      - run: flutter build appbundle

