name: android starter workflow

on:
  push:
    branches: [ "android" ]
  pull_request:
    branches: [ "android" ]

env:
  AAAA: "${{vars.AAA}}"

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          ref: 'b1b8f97b82e0fdb50b3105d86aa604d024000ee7'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml # path to pubspec.yaml
      - run: flutter gen-l10n
      - run: flutter build appbundle

